version: "3"

services:

  redis:
    container_name: redis
    hostname: redis
    image: redis:latest
    restart: on-failure
    ports:
      - "6379:6379"
    networks:
      - web

networks:
  web:
    driver: bridge